services:
  - type: web
    name: oip-backend
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      npm install
      npm run build
      npm run react-build
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # Add your database and other secrets in the Render dashboard
      # Exchange API Keys
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: DERIV_API_KEY
        sync: false
      - key: KRAKEN_API_KEY
        sync: false
      - key: KRAKEN_SECRET_KEY
        sync: false
      - key: KUCOIN_API_KEY
        sync: false
      - key: KUCOIN_SECRET_KEY
        sync: false
      - key: KUCOIN_PASSPHRASE
        sync: false
      # Payment Processors
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_SECRET
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      # Email
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: OIP Trading Bot
      - key: SENDGRID_API_KEY
        sync: false

